### ISSUE TITLE
about cuda

### ISSUE THREAD

**Issue by 17qingyu** [Yangxc13/sparse_tools#1]
Hello, I noticed that you commented out the 'cuda' related content in '__init__.py' and 'setup.py'. Does this mean there are some problems with the cuda part?

**Comment by 17qingyu** [comment]
When I import cuda-related pyd, the following error will occur ''[WinError 193] %1 is not a valid Win32 application"

**Comment by Yangxc13** [comment]
This small tool is designed for the pre-processing step in SeHGNN. As this procedure executes only once during training and actually it does not take much time on cpu, **I did not implement the code on cuda**. If you wish to implement the CUDA version yourself, please refer to the framework of [torch_sparse](https://github.com/rusty1s/pytorch_sparse).

Additionally, this error message may result from the absence of certain essential function definitions when compiling it on a Windows system with cuda. You can attempt to uncomment lines  11, 12, 13, 15 in `./csrc/spspmm_diag.cpp` and `csrc/spspmm_diag_unsym.cpp`.

**Comment by 17qingyu** [comment]
> This small tool is designed for the pre-processing step in SeHGNN. As this procedure executes only once during training and actually it does not take much time on cpu, **I did not implement the code on cuda**. If you wish to implement the CUDA version yourself, please refer to the framework of [torch_sparse](https://github.com/rusty1s/pytorch_sparse).
> 
> Additionally, this error message may result from the absence of certain essential function definitions when compiling it on a Windows system with cuda. You can attempt to uncomment lines 11, 12, 13, 15 in `./csrc/spspmm_diag.cpp` and `csrc/spspmm_diag_unsym.cpp`.

Thank you, I will try your suggestion
